### PR TITLE
fix: coerce python version to semver

### LINKED ISSUE #134: Error running on Ubuntu 18.04 LTS
Running the forward-mail package on Ubuntu 18.04 LTS on a GCP virtual machine fails because of some semver error because the python version installed is Python 2.7.15rc1

Will elaborate and post stack trace when I reach home.

### PR DESCRIPTION
**Pull request by radiantly**
To fix niftylettuce/forward-email#134

### CODE REVIEW

**Review by niftylettuce — CHANGES_REQUESTED** [review]
@radiantly why did you add `stdout` here?  `python --version` reports to stderr afaik for all versions.

**Comment by niftylettuce** [comment]
we'll also need to make the same PR/change in https://github.com/niftylettuce/python-dkim-verify/pull/1/commits/c5db6545a6640ac70e0f396c61f38da378b7c764

**Comment by radiantly** [comment]
I copied the format from python-dkim-verify, where the silent flag was set to false when testing.

```javascript
const silent = process.env.NODE_ENV !== 'test';
const options = { silent, async: true };

// ensure python v2.7+ or v3.5+
let version = exec('python --version', { silent });
version = (version.stdout ? version.stdout : version.stderr)
  .split(' ')[1]
  .trim();
```

What do you think?

**Comment by radiantly** [comment]
@niftylettuce

**Comment by radiantly** [comment]
ping @niftylettuce see my comment above

**Comment by niftylettuce** [comment]
Actually, I like `semver.coerce` better.  I've fixed this in both packages we use internally and also version bumped them.  Thanks so much @radiantly for the nice fix.

**Pull request closed without merging**
